project1 = Project.create(title: "Orangeyouglad", description: "project 1", image_url: "https://53525363.000webhostapp.com/Images/_.jpeg", created_at: Time.now, updated_at: Time.now)
project2 = Project.create(title: "VitaminC", description: "project 2", image_url: "https://53525363.000webhostapp.com/Images/Creative%20Inspiration%20Lettering%20by%20Belinda%20Kou%20_%20Typography%20_%20Graphic%20Design%20Junction%20(1).jpeg", created_at: Time.now, updated_at: Time.now)
project3 = Project.create(title: "Detailed Nasi", description: "project 3", image_url: "https://53525363.000webhostapp.com/Images/Free%20Vector%20_%20Detailed%20nasi%20lemak%20dish.jpeg", created_at: Time.now, updated_at: Time.now)
project4 = Project.create(title: "Buildings", description: "project 4", image_url: "https://53525363.000webhostapp.com/Images/Leonie%20Despres.png", created_at: Time.now, updated_at: Time.now)
project5 = Project.create(title: "Cucumber Patch", description: "project 5", image_url: "https://53525363.000webhostapp.com/Images/Pin%20by%20cindy%20wang%20on%20Ref@DC%20_%20Concept%20art,%20Art%20inspiration,%20Kawaii%20art.jpeg", created_at: Time.now, updated_at: Time.now)
project6 = Project.create(title: "la petite", description: "project 6", image_url: "https://53525363.000webhostapp.com/Images/Postcards%20from%20a%20Pandemic.jpeg", created_at: Time.now, updated_at: Time.now)
project7 = Project.create(title: "Studio Ghibli", description: "project 7", image_url: "https://53525363.000webhostapp.com/Images/Studio%20Ghibli%20on%20Twitter.jpeg", created_at: Time.now, updated_at: Time.now)
project8 = Project.create(title: "AOI", description: "project 8", image_url: "https://53525363.000webhostapp.com/Images/The%20AOI%20-%20Nicholas%20Stevenson.png", created_at: Time.now, updated_at: Time.now)
project9 = Project.create(title: "Teens at home", description: "project 9", image_url: "https://53525363.000webhostapp.com/Images/UNICEF%20-%20Teens%20at%20Home.png", created_at: Time.now, updated_at: Time.now)

BlogPost.create(title: "Orangeyouglad", project_id: project1.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "VitaminC", project_id: project2.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "Detailed Nasi", project_id: project3.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "Buildings", project_id: project4.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "Cucumber Patch", project_id: project5.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "la petite", project_id: project6.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "Studio Ghibli", project_id: project7.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "AOI", project_id: project8.id, created_at: Time.now, updated_at: Time.now)
BlogPost.create(title: "Teens at home", project_id: project9.id, created_at: Time.now, updated_at: Time.now)